spring:
  application:
    name: Hackon

  # Utilizar apenar no Debug
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # Desativa a config automatica e retira a necessidade de um DB pre configurado

  # Utilize este configuração apenas para DEBUG em desenvolvimento
  security:
    csrf:
      enabled: false
    # Usuario e senha temporarios
    user:
      name: admin
      password: 1234
    default-target-url: /home